# Generated by Django 4.0.6 on 2022-08-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_blog_image_user_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_blog',
            old_name='author',
            new_name='saved_by',
        ),
    ]
