# Generated by Django 4.0.6 on 2022-08-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_author_user_blog_saved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_blog',
            old_name='saved_by',
            new_name='author',
        ),
    ]
