# Generated by Django 4.0.6 on 2022-08-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_saved_by_user_blog_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Blog',
        ),
    ]
